# -*- coding: utf-8 -*-
"""Blotter_Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tcRcnzpvZ3ZYTCTd3EcarEXudGnL7Igg
"""

import json

with open('/content/BLOTTER.json','r') as file:
  data = json.load(file)

print(data)

import pandas as pd

# Create a DataFrame from the data
df = pd.DataFrame(data, columns=['Ticker Name', 'Notional', 'Size'])

# Filter out rows where 'Ticker Name' is empty
df_cleaned = df[df['Ticker Name'] != ''].reset_index(drop=True)

#display(df_cleaned)

df_cleaned.head()

# Export the cleaned DataFrame to an Excel file
excel_file_path = '/content/BLOTTER_cleaned.xlsx'
df_cleaned.to_excel(excel_file_path, index=False)

print(f"DataFrame exported to {excel_file_path}")

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile blotter_app.py
# 
# import streamlit as st
# import pandas as pd
# import json
# 
# # --- Load and Prepare Data ---
# @st.cache_data
# def load_data():
#     with open('/content/BLOTTER.json', 'r') as file:
#         data = json.load(file)
#     df = pd.DataFrame(data, columns=['Ticker Name', 'Notional', 'Size'])
# 
#     # Fix: Correctly filter out rows where 'Ticker Name' is empty
#     df_cleaned = df[df['Ticker Name'] != ''].reset_index(drop=True)
# 
#     # Fix: Correct syntax for pd.to_numeric errors argument
#     df_cleaned['Notional'] = pd.to_numeric(df_cleaned['Notional'], errors='coerce')
# 
#     return df_cleaned
# 
# df_cleaned = load_data()
# 
# # --- Streamlit App Layout ---
# st.set_page_config(layout="wide")
# st.title('Interactive Blotter Analysis')
# 
# st.markdown("""
# This interactive dashboard allows you to explore and filter the blotter data.
# Use the sidebar controls to narrow down your view.
# """)
# 
# # --- Sidebar Filters ---
# st.sidebar.header('Filter Options')
# 
# # Ticker Name Filter
# ticker_options = df_cleaned['Ticker Name'].unique().tolist()
# selected_tickers = st.sidebar.multiselect(
#     'Select Ticker Name(s)',
#     options=ticker_options,
#     default=ticker_options
# )
# 
# # Notional Range Filter
# min_notional = df_cleaned['Notional'].min()
# max_notional = df_cleaned['Notional'].max()
# notional_range = st.sidebar.slider(
#     'Notional Range',
#     min_value=float(min_notional),
#     max_value=float(max_notional),
#     value=(float(min_notional), float(max_notional))
# )
# 
# # --- Apply Filters ---
# # Fix: Correctly apply filters and define 'filtered_df'
# filtered_df = df_cleaned[df_cleaned['Ticker Name'].isin(selected_tickers)]
# filtered_df = filtered_df[
#     (filtered_df['Notional'] >= notional_range[0]) &
#     (filtered_df['Notional'] <= notional_range[1])
# ]
# 
# # --- Display Results ---
# st.subheader('Filtered Blotter Data')
# st.dataframe(filtered_df, use_container_width=True)
# 
# st.subheader('Summary Statistics')
# st.write(filtered_df.describe())

